### ISSUE TITLE
calls same api within app even after restart, Url cached?

### ISSUE THREAD

**Issue by jacksondmello** [rishavk1102/Better-Buys-API#1]
ISSUE : Once you run app after fetching from sellers api it displays all sellers. now insert one row in sellers table and look in the app , it loads the same old data when you use print response.body.. it doesn't print or displays this new seller data.. when u call the api seller in browser it loads all data but within app it doesnt display. Please help

**Comment by rishavk1102** [comment]
Hello brother,

What you are saying is highly unlikely, I suggest you to clear your device cache and try again

**Comment by jacksondmello** [comment]
Hi Rishav,
Thank you so much for responding..

I have used the exact same api's which you have provided and hosted in my server and took the api link..
kindly follow below steps and let me know if you face the error
1. run the app
2. now through postman register/insert a new seller with unique email address
3. hot restart and see if the new data loads, for me it loads the old data itself but in browser when i call seller.php api it loads all the records.
4. even deleting a record from seller table directly in my sql has same issue within the app. even in terminal when i use print it displays the same old records.

Please let me know if you face this issue after following above, if you do not face same issue then may be i have to reinstall flutter and check again.

thanks for your support.. Your tutorials are very helpful.

**Comment by rishavk1102** [comment]
Can you please let me know the url you are sending request to from Postman and from within the app

**Comment by jacksondmello** [comment]
Hi Rishav,
can i get your email address or contact detail please , so i can share the link.

**Comment by rishavk1102** [comment]
Surely, hi@whoisrishav.com

**Comment by rishavk1102** [comment]
Anyways, if you are using whoisrishav.com/pk/ and following in your app, then let me tell you that is hosted api on my web server and you can't edit it, you can only access the data.

If you want to use your local database, then use your local url, which will be something like http://localhost:8888/...
